server.port: 34725

solon.app:
  name: 'alinesno-kubernetes-crawler'
  group: 'scheduler-plugin'

solon.logging.appender:
  console:
    level: DEBUG
  file:
    name: "${user.home}/solon-logs/${solon.app.name}"
    rolling: "${user.home}/solon-logs/${solon.app.name}_%d{yyyy-MM-dd_HH_mm}/%i.log"
    level: DEBUG
    maxFileSize: "10 GB"
    maxHistory: "14"

tools:
  crawler:
    parse: vuepress
    site: http://portal.infra.linesno.com